Controllers/AccessController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MVC1.Models;
using BCrypt.Net;

namespace MVC1.Controllers
{
    public class AccessController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string user, string password)
        {
            try
            {
                using (Clasifica db = new Clasifica())
                {
                    // Obtener usuarios que cumplan con los criterios del correo y el status
                    var activeUsers = from u in db.users
                                      where u.email == user && u.idStatus == 1
                                      select u;

                    foreach (var userEntity in activeUsers)
                    {
                        if (BCrypt.Net.BCrypt.Verify(password, userEntity.password))
                        {
                            // Inicio de sesión exitoso
                            Session["User"] = userEntity;
                            return Content("1");
                        }
                    }

                    // Cuando el usuario es incorrecto
                    return Content("Usuario sin Acceso");
                }
            }
            catch (Exception ex)
            {
                return Content("Error de aplicativo: " + ex.Message);
            }
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//importar el models 
using MVC1.Models;
using MVC1.Models.TableViewModels;

//Agreamos el modelo de nuestro formulario
using MVC1.Models.ViewModels;
using WebGrease.Css.Extensions;

namespace MVC1.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            //Creamos una Lista
            List<UserTableViewModel> lst = null;
            using(Clasifica db = new Clasifica())
            {
                //Llenamos la lista
                lst = (from d in db.users
                      where d.idStatus == 1
                      orderby d.email
                      select new UserTableViewModel
                      {
                          Email = d.email,
                          Id = d.id,
                          Edad = d.edad
                      }).ToList();


            }


            return View(lst);
        }

        [HttpGet] //metodo
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost] //metodo
        public ActionResult Add(UserViewModel model)
        {

            if (!ModelState.IsValid) //validando los dataanotation
            {
                return View(model);
            }

            using( var db = new Clasifica())
            {
                user oUser = new user();
                oUser.idStatus = 1;
                oUser.email = model.Email;
                oUser.edad =model.Edad;
                oUser.password = model.Password;

                db.users.Add(oUser);
                db.SaveChanges();
            }

            return Redirect(Url.Content("~/User/"));

        }


        //Meteod para edtiar  si no le pondemos httpget por defecto lo es
        public ActionResult Edit(int Id)
        {
            EditUserViewModel model = new EditUserViewModel();

            using (var db= new Clasifica())
            {
                var oUser = db.users.Find(Id);
                //llenamos el model
                model.Edad = (int)oUser.edad; //porque permite nullos
                model.Email = oUser.email;
                //No ponemos pasww porque no se puede ver
                model.Id = oUser.id;

            }

            return View();
        }

        [HttpPost]
        public ActionResult Edit(EditUserViewModel model) //Recibe modelo
        {
            if (!ModelState.IsValid) //validando los dataanotation
            {
                return View(model);
            }

            using (var db = new Clasifica())
            {
                var oUser = db.users.Find(model.Id);
                oUser.edad = model.Edad;
                oUser.email = model.Email;
                if(model.Password!=null && model.Password.Trim()!="")
                    {
                    oUser.password = model.Password;

                }
                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;  //le decimos al entity que se edita
                db.SaveChanges();
            }


            return Redirect(Url.Content("~/User/"));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
					<li>@Html.ActionLink("Usuarios", "Index", "User")</li>
					<li>@Html.ActionLink("Cerrar sesión", "Logogg", "Access")</li>

				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        
        @RenderBody()
       
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema de Facturación en la nube </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			
		</div>
	</div>
	<div class="container body-content">


		@RenderBody()

		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - Sistema de Facturación en la nube </p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>